### ISSUE TITLE
Incorrect handling of Variables when JOINING from different connectors 

### ISSUE THREAD

**Issue by TristenHarr** [hasura/ndc-jvm-mono#16]
When a relationship is setup from a Postgres table to a MySQL table like this:

```
---
kind: Relationship
version: v1
definition:
  name: openedx_user
  sourceType: Users
  target:
    model:
      name: AuthUser
      relationshipType: Object
  mapping:
    - source:
        fieldPath:
          - fieldName: id
      target:
        modelField:
          - fieldName: id
```

Then a query is issued:

```
query MyQuery {
  users {
    id
    openedx_user {
      email
    }
  }
}
```

There is an error and the generated SQL is incorrect. The generated SQL is:
```
select json_object('rows', (
  select json_arrayagg(json_object('email', email))
  from (
    select auth_user.email as email
    from auth_user
    where auth_user.id = vars.$id
    group by auth_user.email
  ) as auth_user
))
```

See these logs:

```
{"timestamp":"2024-10-15T18:27:02.572281713Z","sequence":78,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.hasura.ndc.app.application.ExceptionHandler","level":"ERROR","message":"Uncaught exception","threadName":"executor-thread-1","threadId":21,"mdc":{"spanId":"065acd5bce897457","parentId":"b2186b9247145014","traceId":"f1e82243cae6daed831f3555f000a8d3","sampled":"true"},"ndc":"","hostName":"09dadc6602b4","processName":"quarkus-run.jar","processId":1,"exception":{"refId":1,"exceptionType":"org.jooq.exception.DataAccessException","message":"SQL [select json_object('rows', (\n  select json_arrayagg(json_object('email', email))\n  from (\n    select auth_user.email as email\n    from auth_user\n    where auth_user.id = vars.$id\n    group by auth_user.email\n  ) as auth_user\n))]; Unknown column 'vars.$id' in 'where clause'","frames":
```
